### PR TITLE
Add german and french translations

### PR DESCRIPTION
**Pull request by er1c**
I haven't technically tested these because I'm doing translations for this differently (just matching the english text, and then using my own localization library - as a side-note it would be really cool to have a way for getWarnings to return back the CONST value for the lookup for doing my own pattern matching against), but thought I'd create a PR with them in the `.properties` format.

Is there a good way to test this via a unit test?

### CODE REVIEW

**Comment by vvatanabe** [comment]
@er1c Thanks for your PR. I will chk it asap.

**Comment by tsuyoshizawa** [comment]
messages_de.properties and messages_fr.properties have different lines.
They should have same lines with empty line.

42 lines is correct.
https://github.com/nulab/zxcvbn4j/tree/master/src/main/resources/com/nulabinc/zxcvbn

**Comment by echox** [comment]
Hi, since I needed the german translation I've added my own one (see https://github.com/nulab/zxcvbn4j/pull/88).

The file in this pull-request has broken umlauts (compare 'Wˆrter' which should be 'Wörter') and sounds a little bit off in some places.

**Comment by vvatanabe** [comment]
I've included this commit in #89 and merged it in. Thanks!

**Pull request closed without merging**
