### PR TITLE
Use CharSequence not String as input type for Zxcvbn.measure

### PR DESCRIPTION
**Pull request by SteveLeach-Keytree**
Issue 31 - change parameter type for Zxcvbn.measure() from String to CharSequence.

This gives a lot more flexibility in what format the password can be in.
The Strength object that is returned also now has a wipe() method to clear sensitive content.
This patch also attempts to avoid using Strings for any sensitive intermediate objects.

### CODE REVIEW

**Comment by SteveLeach-Keytree** [comment]
This patch resolves issue #31.

**Comment by SteveLeach-Keytree** [comment]
I'd be interested to know whether the changes to DictionaryGuess.uppercaseVariations are safe. I've switched from regular expression matching strings to comparing characters, as I _believe_ that the code was just counting upper & lower case characters. However, I'm not 100% convinced that the new code has exactly the same results as the old code in all possible cases. Does it matter?

**Comment by vvatanabe** [comment]
@SteveLeach-Keytree 
Sorry for the late reply, and thank you for the great pull request.

I think there is no problem switching from regular expression matching strings to character comparisons.

Please take a moment to review. Thanks.

**Comment by SteveLeach-Keytree** [comment]
> Please take a moment to review. Thanks.
Sorry, I'm not that familiar with the Github PR workflow. What exactly would you like me to review?

**Comment by SteveLeach-Keytree** [comment]
Hi @vvatanabe - could you clarify what I need to review, and if there is anything else I need to do to get this PR merged?

**Comment by SteveLeach-Keytree** [comment]
While waiting for this PR to be merged I thought I might as well investigate and fix issue #49, so that is now also covered by this PR.

**Comment by SteveLeach-Keytree** [comment]
Are there any other maintainers who can merge this?

**Comment by SteveLeach-Keytree** [comment]
Is this project dead now?

**Comment by vvatanabe** [comment]
@SteveLeach-Keytree 
I'm sorry it took me a while to get back to you. I will merge and release a new version.

**Comment by overheadhunter** [comment]
Thanks for the PR. I was very happy to see this has been implemented in 1.3.0. I was just about to make a PR myself, when I stumbled upon the new release 😄

**Pull request merged**
