### PR TITLE
Added possibility to configure with whitelists what resources(diction…

### PR DESCRIPTION
**Pull request by lumarino**
…aries and keyboards) should be used to calculate stength-scores, thus also enabling to use custom resources

### CODE REVIEW

**Comment by lumarino** [comment]
The creator this Issue is a former collegue of mine, this PR should solve this Issue: https://github.com/nulab/zxcvbn4j/issues/70

**Comment by vvatanabe** [comment]
@lumarino Sorry for the late reply. This custom dictionary and keyboard feature looks great.
I think dictionaries should be updated with the times. This pull request is currently conflicted. Can you resolve it? I want to merge this pull request.

**Comment by lumarino** [comment]
Hey @vvatanabe , thanks for taking care and reviewing this pull-request, I also thought about this, but the benefit of using files for new dictionaries and keybords is, that it makes the library more flexible, as you said you can add the keyboard as maintainer and the users can configure what dictonaries/keyboards to use, it is also possible to exclude dictionaries allready present in the library, in advance of that they can also add their own ressources in a simple way, and they are added with the same logic as the built in dictionaries/keyboards, if you want to add an API the user would need to parse the dictionary entries himself and pass it to the library, it seems to be the more complicated option, also this would not provide a way add keyboard files.

**Comment by vvatanabe** [comment]
@lumarino
The following pull request allows you to set up a custom dictionary/keyboard using the library API.
This approach allows custom dictionaries and keyboard settings to be defined entirely in code. By abstracting resources with InputStream, files other than classpaths (over HTTP, other directories in server) can also be used. We going to merge it.
https://github.com/nulab/zxcvbn4j/pull/124

HOW TO USE:
src/test/java/com/nulabinc/zxcvbn/ZxcvbnBuilderTest.java
https://github.com/nulab/zxcvbn4j/pull/124/files#diff-ec06d7c12a656368307d2bc5811e2873fcd60a98b03ef01b4b70ddf74fdad82a

Your pull request is also very nice. You have allowed me to think deeply about designing a custom dictionary/keyboard.
Thank you for your contribution to this library.

**Comment by lumarino** [comment]
Hey @vvatanabe, looks good to me, it would be nice of you if you could merge this branch and the other on top of it, or if you would had commited the changes into this MR/branch, anyways I am happy to see this feature inside the project.

**Pull request closed without merging**
