### PR TITLE
Add module-info.java

### LINKED ISSUE #103: Add module-info.java
Since this library has no runtime dependencies, it is a great candidate to now become an explicit module.

Unless it is planned to change this, the target JDK is still Java 7. In order to ensure compatibility with Java 7 and 8, we can't simply add a `module-info.java` to the jar, but we rather need to declare it a multi-release jar in its `MANIFEST.MF`.

I'm happy to create a PR, just let me know!

### PR DESCRIPTION
**Pull request by overheadhunter**
This adds a `module-info.java` and fixes #103.

Note there are two unexpected but necessary changes:

1. I had to disable builds using JDK 8. This is required for building. It _does not_ affect the Java compatibility level, which stays at 7.
2. ~Due to stricter access control mechanisms in modular apps, I had to fix resource loading, which used to facilitate classloader. However, this is not recommended and breaks easily in different scenarios. See [this SO post](https://stackoverflow.com/a/61317159/4014509) for an explanation. Please take care to review this particular change thoroughly!~ Edit: Reverted due to concerns mentioned below

Futhermore, it is worth pointing out that the line `exports com.nulabinc.zxcvbn.matchers;` inside of the module-info is only necessary due to the fact that `com.nulabinc.zxcvbn.matchers.Match` is exposed public API. If this class can be moved to the top-level package, this line can be removed. So from a library user's perspective, both `com.nulabinc.zxcvbn.matchers.*` and `com.nulabinc.zxcvbn.guesses.*` will be hidden.

### CODE REVIEW

**Comment by vvatanabe** [comment]
@overheadhunter 

ResourceLoader.java solves the following problems.
https://github.com/nulab/zxcvbn4j/issues/79

Without the ResourceLoader class, the above problem is likely to recur in various applications using zxcvbn4j.

**Comment by overheadhunter** [comment]
The linked issue was caused by the fact that you used to use `Thread.currentThread().getContextClassLoader()` instead of `getClass().getClassLoader()`.

However, even this is not "correct", see linked StackOverflow Post. I would encourage you to just retest the new implementation, as it is the way resource loading is intended.

**Comment by overheadhunter** [comment]
To simplify review and not delay things further, I've re-added the ResourceLoader (added the described way of loading a resource as a first step, though). Note that the resource URL still needs to be absolute (tbh I wonder how it ever worked in the first place 🙈).

**Comment by vvatanabe** [comment]
@overheadhunter Thank you! I will prepare to release 1.6.0

**Comment by vvatanabe** [comment]
@overheadhunter I got an error in validation after publishing to sonatype. It will take some time to release it.

image

**Comment by vvatanabe** [comment]
@overheadhunter Now I released zxcvbn 1.6.0. Please check Java 9 Modules.

**Comment by overheadhunter** [comment]
@vvatanabe Works like a charm, thank you very much!

**Pull request merged**
